backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    # path("__reload__/", include("django_browser_reload.urls")),
    path('', include('core.urls')),
    path('courses/', include('courses.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib.auth import views
from django.urls import path

from .views import main, profile, signup

urlpatterns = [
	path('', main, name="frontpage"),
	path('signup/', signup, name="signup"),
	path('login/', views.LoginView.as_view(template_name='login.html'), name='login'),
	path('logout/', views.LogoutView.as_view(), name='logout'),
	path('profile/', profile, name="profile"),
]

courses/urls.py
from core.views import add_video, create_course, delete_video
from django.urls import path

from . import views

urlpatterns = [
	path('', views.courses, name="courses-page"),
	path('course/<slug:slug>/', views.course, name="course-page"),
	path('course/payment/<str:id>/', views.course_payment, name="course-payment"),
	path('create_course/', create_course, name='create_course'),
	path('add_video/', add_video, name='add_video'),
	path('delete_video/<int:id>/', delete_video, name='delete_video'),
	path('create_comment/<slug:slug>/', views.create_comment, name="create_comment"),
	path('delete_comment/<int:id>/', views.delete_comment, name="delete_comment")
]

courses/models.py
import uuid

from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
from django.db import models
from django.utils.text import slugify

media = FileSystemStorage(location="/media/thumbnails")

class Course(models.Model):
	id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	slug = models.SlugField(blank=True, null=True)
	thumb = models.ImageField(upload_to='courses/thumbnails/', blank=True, null=True)
	# thumb = models.ImageField(storage=media, blank=True, null=True)
	name = models.CharField(max_length=255)
	price = models.IntegerField(default=25)
	description = models.TextField()

	def __str__(self):
		return self.name
	def save(self, *args, **kwargs):
		if not self.slug:
			self.slug = slugify(self.name)
		super(Course, self).save(*args, **kwargs)

class UserCourse(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	course = models.ForeignKey(Course, on_delete=models.CASCADE)

	def __str__(self):
		return f'{self.user.username} - {self.course.name}'

class Video(models.Model):
	course = models.ForeignKey(Course, on_delete=models.CASCADE)
	name = models.CharField(max_length=255)
	video_file = models.FileField(upload_to='courses/videos/', blank=True, null=True)
	description = models.TextField()

	def __str__(self):
		return self.name

class Orders(models.Model):
	order_id = models.CharField(max_length=500)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	course = models.ForeignKey(Course, on_delete=models.CASCADE)
	date = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f'{self.user} - {self.order_id} - {self.date} - {self.course}'

class Comment(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	course = models.ForeignKey(Course, on_delete=models.CASCADE)
	message = models.TextField(max_length=300)
	date = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f'{self.course} - {self.user} - {self.message} - {self.date}'

courses/views.py
import json

from core.forms import VideoForm
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import Http404
from django.shortcuts import redirect, render
from django.views.decorators.http import require_http_methods

from .models import Comment, Course, Orders, UserCourse, Video


def courses(request):
	courses = Course.objects.all()
	allcourses = []													#every course
	for course in courses:
		allcourses.append(course)
	# user_courses = []
	# i = 0    

	if request.user.is_authenticated and not request.user.is_superuser:
		user_courses_id = UserCourse.objects.filter(user=request.user).values_list('course__id', flat=True)
		available_courses = Course.objects.exclude(id__in=user_courses_id)

		user_courses = []
		for user_course in UserCourse.objects.filter(user=request.user):
			user_courses.append(user_course.course)

			# print(user_courses)

		context = {
			'user_courses': user_courses,
			'available_courses': available_courses,
		}
		return render(request, 'courses.html', context)
	else:
		# courses = Course.objects.all()
		return render(request, 'courses.html', {'available_courses':courses})

# @user_passes_test(lambda u: u.is_superuser)
@login_required
def course(request, slug):
	course = Course.objects.get(slug=slug)

	if request.user.is_superuser or UserCourse.objects.filter(user=request.user, course=course):
		comments = Comment.objects.filter(course=course)
		videos = Video.objects.filter(course=course)
		video_form = VideoForm()

		data = {
			'course':course,
			'videos':videos,
			'video_form':video_form,
			'comments':comments
		}
		return render(request, 'view_course.html', data)
	else:
		comments = Comment.objects.filter(course=course)
		videos = Video.objects.filter(course=course)
		videos_list = []
		first_video = None

		for video in videos:
			videos_list.append(video)
			first_video = videos_list[0].video_file.url
			
		data = {
			'course':course,
			'first_video': first_video,
			'comments':comments
		}
		return render(request, 'course.html', data)

@login_required
@require_http_methods(['POST'])
def course_payment(request, id):
	user_pk = request.user
	course_id = Course.objects.get(pk=id)
	order_data = json.loads(request.body)
	id_value = order_data.get('orderID')

	if course_id and id_value:
		Orders.objects.create(order_id=id_value, user=user_pk, course=course_id)
		UserCourse.objects.create(user=user_pk, course=course_id)

		# print(id_value)
		return redirect(request.META['HTTP_REFERER'])
	else:
		raise Http404('Page not found.')

@login_required
@require_http_methods(['POST'])
def create_comment(request, slug):
	course = Course.objects.get(slug=slug)
	message = request.POST.get('message')

	Comment.objects.create(user=request.user, course=course, message=message)
	return redirect(request.META['HTTP_REFERER'])

@login_required
@require_http_methods(['POST'])
def delete_comment(request, id):
	if Comment.objects.filter(user=request.user): 				#if the comment belongs to the authenticated user...
		Comment.objects.get(id=id, user=request.user).delete()  #delete said comment
		return redirect(request.META['HTTP_REFERER']) 			#refresh page
	elif request.user.is_superuser:
		Comment.objects.get(id=id).delete()
		return redirect(request.META['HTTP_REFERER'])
	else:
		raise Http404('There has been a mistake...?')			#if it's a dif user, raising 404

courses/templates/course.html
{% extends "base.html" %}
{% block title %}{{course.name}}{% endblock title %}
{% load static %}
{% block styles %}
	<style>
		.course{
			width: 100%;overflow: hidden;
			height: 100%;
			display: flex;flex-direction: row;
			background: var(--a);
		}
		.course span{color: var(--e);}
		.course-l{
			background: var(--a);
			width: 50vw;
			height: 85vh;
			overflow-y: scroll;
			display: flex;flex-direction: column;
			align-items: center;justify-content: start;
			color: #fff;
			padding: 1rem 0;
		}
		.course-l h1{
			text-align: center;margin-bottom: 2rem;
		}
		.course-l img{
			width: 80%;
			margin-bottom: 2rem;
			border-bottom:1px solid var(--c);padding-bottom: 2rem;
			/* transform: rotate(-5deg) translateY(2rem); */
		}
		.course-info{
			background: #fff;
			width: 50vw;
			padding: 2rem;
			animation: showR .5s ease-out;
		}
		.course-info p{color: #888;margin-top: .5rem;margin-bottom: .5rem;}

		.course-l video{
			width: 80%;margin-top: 1rem;
			border-top: 1px solid var(--c);
			padding-top: 2rem;
		}
		.test-button{
			padding: .5rem;border-radius: 5px;
			background: #400;color: #fff;
			width: 100%;text-align: center;
			margin-top: .5rem;
		}
	</style>
{% endblock styles %}

{% block main %}
    <section class="course">
    	<div class="course-l">
    		<img src="{{course.thumb.url}}" alt="{{course.name}}">
    		
    		<h1>{{course.name}}</h1>

    		<p><span>$25</span> and you'll keep it forever.</p>

    		{% if first_video != None %}
    		<h3>Here you have a quick peek:</h3>
    		    
    		<video class="sneekpeek" controls autoplay="autoplay" loop>
    			<source src="{{first_video}}" type="video/mp4">
    		</video>
    		{% endif %}

    		
    	</div>
    	
    	<div class="course-info">
    		<h4>Introduction:</h4>

    		<p>{{course.description}}</p>

    		<h4>Length:</h4>

    		<p>10 videos</p>

    		<h4>Video Length:</h4>

    		<p>60 minutes</p>

    		<h4>Price:</h4>

    		<p>$ 25</p>

    		<div id="paypal-button-container"></div>
    		<p class="test-button">Warning: this is a test button!</p>
    	</div>
    </section>
{% endblock main %}

{% block scripts %}
	<script src="https://www.paypal.com/sdk/js?client-id=AQkqf5Ad-9tc8qiT_y5RBBJyQdWcFz_oyzzdgJYNYyVVPJVqewjXFPrzrPXVO1mefUi7gbdxO1S15yrF&components=buttons"></script>
    <script>
    	paypal.Buttons({
			style: {
				layout: 'vertical',
				color:  'blue',
				shape:  'rect',
				label:  'paypal'
			},
			createOrder: function(data, actions){
				return actions.order.create({
					purchase_units: [{
						amount: {
							value: '25'
						}
					}]
				});
			},
			onApprove: function(data, actions) {
				return actions.order.capture().then(function(details) {
        // This function shows a transaction success message to your buyer.
					const csrftoken = document.querySelector('input[name="csrfmiddlewaretoken"]').value;
		            
		            fetch('{% url "course-payment" course.id %}', {
		            	method: 'POST',
		    			headers: {
		    				'Content-Type': 'application/json',
							'X-CSRFToken': csrftoken
		    			},
		    			body: JSON.stringify({orderID: details.id})
		            })
		            .then(response => {
		            	console.log(response)
		            	alert('Transaction completed by ' + details.payer.name.given_name);
		            	window.location.assign("/courses");
		            })
		            .catch(error => {
		            	console.error(error)
		            })
		        });
			},
			onCancel: function(data){
				alert('Payment cancelled.')
			}
		}).render('#paypal-button-container');
    </script>
{% endblock scripts %}

courses/templates/courses.html
{% extends "base.html" %}

{% block title %}Courses{% endblock title %}
{% load static %}
{% block styles %}
    <style>
    	.courses{
    		padding: 2rem;
    		width: 100%;height: 100%;
    		min-height: 75vh;
    	}

    	.courses ul{
    		display: flex;flex-direction: column;
    		width: 100%;height: 100%;
    		gap: 2rem;
    		margin-top: 2rem;
    	}
    	.courses ul li{
    		display: flex;flex-direction: row;
    		width: 100%;
    		/* height: 100%; */
    		align-items: start;justify-content: start;
    		gap: 1rem;
    		overflow: hidden;
    	}
    	.courses ul li:hover img{opacity: 1}
    	.courses ul li img{
    		width: 480px;
    		border-radius: 1rem;
    		opacity: .8;
    		transition: .4s;
    	}
    	.course-about{display: flex;flex-direction: column;justify-content: space-between;height:270px;width: 100%;}
    	.course-about-txt{display: flex;flex-direction: column;}
    	.course-about span{color: var(--c);}
    	.course-about h3{font-size: 2rem;margin-bottom: 1rem;}	.course-about p{color: #ccc;}
    	.course-about a{text-align: center;font-size: 2rem;width: 100%;}
    </style>
{% endblock styles %}

{% block main %}
    
	<section class="courses">
		<h1>Learn by watching entertaining videos!</h1>

		<ul>
			{% if available_courses %}
			    
				{% for course in available_courses %}
					
				<li>
					<img src="{{course.thumb.url}}" alt="{{course.name}}">

					<div class="course-about">
						<div class="course-about-txt">
							<h3>{{course.name}}</h3>
							<p>{{course.description}}</p>
						</div>
						<a href="{% url 'course-page' course.slug %}" class="btn1">Buy this Course <i class="fa-brands fa-paypal"></i></a>    
					</div>
				</li>

				{% endfor %}

			{% else %}
			    <h4>This place is empty. <br> Come back soon...</h4>
			{% endif %}

			{% if user_courses %}

			{% for course in user_courses %}
				<li>
					<img src="{{course.thumb.url}}" alt="{{course.name}}">

					<div class="course-about">
						<div class="course-about-txt">
							<h3>{{course.name}}</h3>
							<p>{{course.description}}</p>
						</div>
						<a href="{% url 'course-page' course.slug %}" class="btn3">You own this item <i class="fa-solid fa-arrow-right"></i></a>
					</div>
				</li>
			{% endfor %}

			{% endif %}
		</ul>
	</section>

{% endblock main %}

courses/templates/view_course.html
{% extends "base.html" %}
{% block title %}{{course.name}}{% endblock title %}
{% load static %}
{% block styles %}
    <style>
    	.course{
    		background: #111;
    		width: 100%;height: 100%;
    		color: #fff;
    		padding: 2rem;

    	}
    	.course-videos{
    		width: 100%;height: 100%;
    		display: flex;flex-direction: column;
    		align-items: center;justify-content: start;
    		gap: 2rem;
    	}
    	.course-video{
    		/* width: 100%; */
    		height: 100%;width: initial;
    		padding: 2rem;
    		/* background: var(--b); */
    		/* box-shadow: 0 5px 10px #003; */
    		border-radius: 5px;
    		overflow: hidden;
    	}

    	.course-video video{
    		border-radius: 5px;
    		width: 1280px;height: 720px;
    	}
    	.course-video h4{font-size: 2rem;margin-top: 1rem;}
    	.course-video p{color: #eee;}
    	.number{
    		color: var(--e);
    		text-shadow: 2px 2px #003;
    		font-size: 3rem;
    	}
    	.course-title{
    		width: 1280px;text-align: center;
			border-top: 1px solid var(--b);
			padding-top: 1rem;
			margin:0 auto;
    	}
    	.add_video{
    		display: flex;flex-direction: column;
    		width: 400px;height: 100%;
    		overflow: hidden;
    		align-items: center;justify-content: start;
    		padding: 1rem;
    		box-shadow: 0 5px 10px #003;border-radius: 5px;
    		background: var(--b);
    	}
    	.add_video input{color: #000;width: 90%;}
    	.add_video input[type='file']{
    		display: none;
    	}
    	.add_video textarea,
    	.add_video select{
    		width: 90%;
    		padding: .5rem;
    		border-radius: 5px;border:none;
    		background: #f1f1f1;
    		font-size: 1rem;
    		resize:vertical;
    	}
    	.add_video label:nth-of-type(3){display: none;}
    	#videoButton{
    		padding: 1rem;
    		width: 90%;text-align: center;
    		color: #fff;transition:.3s;
    		background: #000;border-radius: 5px;
    	}
    	#videoButton:hover{
    		background: var(--d);
    	}
    	.add_video .btn1{margin-top: 1rem;}
    	.course-description{
    		width: 50%;
    		margin: 0 auto;
    		color: #eee;
    		margin-top: 1rem;margin-bottom: 2rem;
    		
    		padding-bottom: 1rem;
    		border-bottom: 1px solid var(--b);
    	}
    	.comments{
    		display: flex;flex-direction: column;
    		width: 100%;
    		
    		gap: 1rem;
    		margin: 1rem 0;
    	}
    	.comment{
    		/* width: 100%; */
    		position: relative;
    		display: flex;flex-direction: column;
    		gap: .5rem;
    		padding-bottom: .5rem;margin-bottom: .5rem;
    		border-bottom: 1px solid var(--b);
    	}
    	.make-comment{
    		display: flex;flex-direction: column;
    		width: 500px;height: 200px;
    		/* padding: 1rem; */
    		overflow: hidden;
    		margin: 0 auto;
    	}
    	.make-comment textarea{
    		padding: .5rem;font-size: 1rem;
    		font-family: sans-serif;color: #111;
    		background: #f1f1f1;border:none;
    		border-radius: 5px;resize:none;
    		height: 100%;margin-bottom: .5rem;
    	}
    	.comment form{
    		position: absolute;
    		right: 0;bottom: .5rem;
    	}
    </style>
{% endblock styles %}

{% block main %}
    <section class="course">

    	<h1 class="course-title">{{course.name}}.</h1>
    	<p class="course-description">{{course.description}}</p>

    	<div class="course-videos">
    		
			{% for video in videos %}
    		<div class="course-video">
    			
				<video class="contentVideo" controls="controls" controlslist="nodownload">
					<source src="{{video.video_file.url}}" type="video/mp4">
				</video>

				<h4>{{video.name}}</h4>
				<p>{{video.description}}</p>

				{% if request.user.is_superuser %}
				<form action="{% url 'delete_video' video.id %}" method="post">
					{% csrf_token %}
					<button class="btn3"><i class="fa-solid fa-trash"></i></button>
				</form>
				{% endif %}

    		</div>
			{% endfor %}



			<section class="comments">
				
				<form action="{% url 'create_comment' course.slug %}" method="post" class="make-comment">
					{% csrf_token %}
					<textarea name="message" cols="30" required placeholder="Comment something"></textarea>
					<button class="btn1">Comment</button>
				</form>

				{% if comments %}
				{% for comment in comments %}
				<div class="comment">
					<h3>{{comment.user}}</h3>
					<p>{{comment.message}}</p>
					<span>{{comment.date}}</span>

					{% if request.user == comment.user or request.user.is_superuser %}
					<form action="{% url 'delete_comment' comment.id %}" method="post">
						{% csrf_token %}
						<button class="btn3"><i class="fa-solid fa-trash"></i></button>
					</form>
					{% endif %}
				</div>
				{% endfor %}
				{% else %}
				<div class="comment">
					<h3>Comments will show up down here <i class="fa-solid fa-arrow-down"></i></h3>
				</div>
				{% endif %}

			</section>



			{% if request.user.is_superuser %}
			<form class="add_video" id="add_video_form" action="{% url 'add_video' %}" method="POST" enctype="multipart/form-data">
				{% csrf_token %}

				<p>Video:</p>

				<a href="#add_video_form" id="videoButton"><i class="fa-solid fa-video"></i></a>
				{{video_form}}

				<button class="btn1">Submit</button>
			</form>
			{% endif %}

    	</div>

    </section>
{% endblock main %}

{% block scripts %}
    <script>
    	const contentVideos = document.querySelectorAll('.contentVideo')

		document.addEventListener('DOMContentLoaded', function() {
    
			contentVideos.forEach(function(contentVideo) {
				contentVideo.addEventListener('contextmenu', function(event) {
					event.preventDefault();
				});
			});
		
		});
    </script>
    <script>
		const courseVideos = document.querySelectorAll('.course-video');
		const videoInput = document.querySelector('#id_video_file')
		const videoButton = document.querySelector('#videoButton')
		let count = 1;

		courseVideos.forEach(video => {
			const p = document.createElement('p');
			p.classList.add('number');
			p.textContent = count++;
			// video.insertAdjacentElement('afterend', p)
			video.parentNode.insertBefore(p, video);
		});

		videoButton.addEventListener('click', function(){
			videoInput.click()
		})
    </script>
{% endblock scripts %}